version: '3.8'
services: 
  redis: 
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  flower:
    image: mher/flower
    container_name: flower
    environment:
    - FLOWER_UNAUTHENTICATED_API=true  # <-- Permite acceso sin credenciales
    command: celery --broker=redis://redis:6379/0 flower --port=5555
    ports:
      - "5555:5555"
    depends_on:
      - redis

  orquestador:
    build: ./orquestador
    ports: 
      - "8000:8000"
    volumes:
      - ./shared_vol:/shared
      - ./orquestador:/app
    depends_on:
      - redis
      - peticiones-service
      - detector-service
      - qrdetector-service
      - tracker-service
      - nubes-service

  detector-service:
    build: ./workers/detectorBayas
    volumes:
      - ./shared_vol:/shared
      - ./workers/detectorBayas:/app
    user: root
    runtime: nvidia
    deploy:         # <-- Configurar reserva de GPU
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all  # Usar todas las GPUs
              capabilities: [gpu, compute, utility]
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,graphics
      - NVIDIA_DISABLE_REQUIRE=1
      - LD_LIBRARY_PATH=/usr/local/cuda-9.2/lib64:${LD_LIBRARY_PATH}
    ports:
      - "8001:8001"

  qrdetector-service: 
    build: ./workers/qrDetectorBayas
    volumes: 
      - ./workers/qrDetectorBayas:/app
      - ./shared_vol:/shared
    ports:
      - "8002:8002"

  tracker-service:
    build: ./workers/trackerBayas
    volumes:
      - ./workers/trackerBayas:/app
      - ./shared_vol:/shared
    ports:
      - "8003:8003"

  nubes-service: 
    build: ./workers/nubesBayas
    volumes:
      - ./workers/nubesBayas:/app
      - ./shared_vol:/shared
    ports:
      - "8004:8004"    

  peticiones-service:
    build: ./workers/peticionesHTTP
    volumes:
      - ./workers/peticionesHTTP:/app
      - ./shared_vol:/shared
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - TRACKER_SERVICE_URL=http://tracker-service:8000
    depends_on:
      - tracker-service

volumes:
  redis_data: 
  shared_volume: 